### ISSUE TITLE
ERROR: result must be a pointer

### ISSUE THREAD

**Issue by droslean** [fenos/dqlx#15]
Can someone help me understand this?

The following code generates the error `result must be a pointer`. 
```go

var data []map[string]interface{}

client.Query(dqlx.HasFn("name")).
		Filter(
                   dqlx.UID("0x12345"),
		).Select(`
		    name
		`).UnmarshalInto(data).Execute(ctx)
```

@fenos

**Comment by fenos** [comment]
Hello,

You need to do exactly what the error says 😊


Passing the pointer of data into the UnmarshallInto function 

&data not data
