### ISSUE TITLE
Expand(_all_) DQL feature

### ISSUE THREAD

**Issue by droslean** [fenos/dqlx#17]
@fenos Is there a way to `.Select()` all of the fields instead? Also, is there a way to inject `expand(_all_)` in the selection?

**Comment by droslean** [comment]
Also, this can be consider as bug, right?

```
  "message": "rpc error: code = Unknown desc = : while converting to subgraph: expand(_all_) not allowed multiple times in same sub-query.",
```

**Comment by droslean** [comment]
@fenos Is there any workaround?

**Comment by fenos** [comment]
Hi @droslean you can try using the `Edge` function something along this line:

```go
Select(`uid`).Edge("expand(_all_)", dqlx.Select(`
       expand(_all_)
`)).
```

**Comment by droslean** [comment]
@fenos I tried what you suggested, but the response still doesn't include any predicates.

**Comment by droslean** [comment]
It seems that the query is constructed with `<expand(_all_)>` instead of `expand(_all_)`. For some reason, dgraph is ignoring the expand if it is surrounded with `<>`.
