### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by fenos** [fenos/dqlx#20]
Unfortunately due to lack of time and passion for Dgraph i'm unable to maintain the project as i'd like to.
If any of you would like to be a maintainer of dqlx please comment below

**Comment by droslean** [comment]
@fenos I am actively using this library but I am using my fork since I fixed a blocker bug. I could start maintaining this project.

**Comment by fenos** [comment]
@droslean Awesome! I'm glad you are finding dqlx useful!
I added you as a maintainer thanks a lot
