### ISSUE TITLE
Cascade directive

### ISSUE THREAD

**Issue by KiVo16** [fenos/dqlx#3]
Hi,
I've not found any information about the @cascade directive in the library's documentation (I assume it's just not supported yet). 

I was thinking about the "ugly" workaround:
- Add @filter(@cascade) at the root level - run ToDQL func - replace string @filter(@cascade) with just @cascade - turn back to QueryBuilder (generally I wanted to update only query string, but I didn't find any solution for turning query, args, and error back into QueryBuilder)

Can you give me a solution on how to add @cascade for my query? It's crucial for one of my functions.

Also, it would be nice to be able to modify the query string more directly with function, which would allow adding custom parts to the query at the root level (next to filters etc.). For example, when Dgraph would release another part of the query, needed to be placed at the root level then it would be easy to implement that part without a specific function from the DQLX package (considering that there isn't a function meant to add that part)

**Comment by fenos** [comment]
This is now supported in version 0.3.0 

feel free to open another issue if you feel like needing another function to customize a query freely
